language: python
python:
  - 3.7

services:
  - postgresql

addons:
  postgresql: "9.4"
  apt:
    packages:
    - postgresql-9.4-postgis-2.4

env:
  global:
    - RABBITMQ_HOST=rabbitmq
    - DATABASE_NAME=travis_ci_test
    - DATABASE_USERNAME=postgres
    - DATABASE_PASSWORD=''
    - DATABASE_HOST=localhost
    - DJANGO_SETTINGS_MODULE=settings_docker

dist: xenial

before_install:
  - python --version
  - pip install -U pip
  - pip install codecov

install:
  - pip install -r ./dockerize/docker/REQUIREMENTS.txt
  - pip install flake8
  - pip install coverage

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'create extension postgis;' -U postgres -d travis_ci_test
  - sudo apt-get -y install python-gdal
  - sudo apt-get -y install python-geoip

script:
  - cd qgis-app
  - flake8 ./api
  - flake8 ./base
  - flake8 ./styles
  - flake8 ./geopackages
  - flake8 ./models
  - python manage.py makemigrations
  - python manage.py migrate
  - coverage run manage.py test api base styles geopackages models

after_success:
  - codecov
